function pol = importPol(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   POL = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   POL = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   pol = importfile('e1233gap_turbulent.pol', 13, 474);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/08/14 11:34:49

%% Initialize variables.
if nargin<=2
    startRow = 13;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%8f%9f%10f%10f%9f%9f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');
if fileID == -1; error(['cannot open ' filename]);end;

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
pol = table(dataArray{1:end-1}, 'VariableNames', {'alpha','CL','CD','CDp','CM','topXtr','botXtr'});
pol = sortrows(pol,1); %sort the table by increasing AOA

